  
# 核心任务

- name: JumpServer
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  

    JumpServer_distribution: "{{JumpServer_select[JumpServer_selection]}}"
  
  pre_tasks:
    - debug:
        msg: Will install {{JumpServer_distribution}}

  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_jdk, tags: "role_jdk"}  
    - {role: jumpserver, tags: "jumpserver"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
