  
# 核心任务

- name: JumpServer
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml
  
  roles:
    - {role: role_common, tags: "role_common"}  
    - {role: role_redis, tags:"role_redis"}
      {role: role_mysql, tags: "role_mysql"}
      {role: role_ngnix, tags: "role_ngnix"}
    - {role: jumpserver, tags: "jumpserver"}
    - {role: role_preend, tags: "preend"}
    - {role: role_end, tags: "role_end"}
